name: Integrate Slack
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#pipeline'
        if: always()
        
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: starting
          channel: '#pipeline'
          message: Deployed to testing Successfully...
        if: always()
